from __future__ import annotations

import json
from pathlib import Path
from textwrap import dedent
from typing import Dict, Any, Optional

from .data import write_sample
from .recommend import get_recommendation, task_hint


def response_markers(chat_template: str) -> Dict[str, Optional[str]]:
    if chat_template == "llama-3.1":
        return {
            "train_on_responses_only": True,
            "instruction_part": "<|start_header_id|>user<|end_header_id|>\n\n",
            "response_part": "<|start_header_id|>assistant<|end_header_id|>\n\n",
        }
    if chat_template in {"chatml", "qwen"}:
        return {
            "train_on_responses_only": True,
            "instruction_part": "<|im_start|>user\n",
            "response_part": "<|im_start|>assistant\n",
        }
    return {"train_on_responses_only": False, "instruction_part": None, "response_part": None}


def default_config(project_name: str, task: str, model_label: str) -> Dict[str, Any]:
    rec = get_recommendation(model_label)
    markers = response_markers(rec.chat_template)
    return {
        "project_name": project_name,
        "task": task,
        "base_model": rec.model,
        "chat_template": rec.chat_template,
        "max_seq_length": rec.max_seq_length,
        "load_in_4bit": True,
        "lora_rank": rec.lora_rank,
        "lora_alpha": rec.lora_rank,
        "lora_dropout": 0,
        "learning_rate": 2e-4,
        "per_device_train_batch_size": 2,
        "gradient_accumulation_steps": 4,
        "warmup_steps": 5,
        "max_steps": 60,
        "num_train_epochs": None,
        "logging_steps": 1,
        "packing": False,
        "seed": 3407,
        "train_file": "data/train.jsonl",
        "eval_file": "data/eval.jsonl",
        "output_dir": "outputs",
        "adapter_dir": "adapters/final",
        "report_to": "none",
        **markers,
    }


TRAIN_PY = r'''#!/usr/bin/env python3
"""Generated by UnslothKit. Edit config.json first; keep this file boring."""
from __future__ import annotations

import json
from pathlib import Path


def load_jsonl_messages(path: str):
    rows = []
    with open(path, "r", encoding="utf-8") as f:
        for line_no, line in enumerate(f, start=1):
            if not line.strip():
                continue
            obj = json.loads(line)
            messages = obj.get("messages") or obj.get("conversations")
            if not messages:
                raise ValueError(f"{path}:{line_no} missing messages")
            rows.append({"messages": messages})
    return rows


def main():
    cfg = json.loads(Path("config.json").read_text())

    from unsloth import FastLanguageModel, is_bfloat16_supported
    import torch
    from datasets import Dataset
    from transformers import DataCollatorForSeq2Seq
    from trl import SFTConfig, SFTTrainer

    max_seq_length = int(cfg["max_seq_length"])
    model, tokenizer = FastLanguageModel.from_pretrained(
        model_name=cfg["base_model"],
        max_seq_length=max_seq_length,
        dtype=None,
        load_in_4bit=bool(cfg.get("load_in_4bit", True)),
        token=cfg.get("hf_token"),
    )

    chat_template = cfg.get("chat_template", "auto")
    if chat_template and chat_template != "auto":
        from unsloth.chat_templates import get_chat_template
        tokenizer = get_chat_template(tokenizer, chat_template=chat_template)

    model = FastLanguageModel.get_peft_model(
        model,
        r=int(cfg["lora_rank"]),
        target_modules=["q_proj", "k_proj", "v_proj", "o_proj", "gate_proj", "up_proj", "down_proj"],
        lora_alpha=int(cfg.get("lora_alpha", cfg["lora_rank"])),
        lora_dropout=float(cfg.get("lora_dropout", 0)),
        bias="none",
        use_gradient_checkpointing="unsloth",
        random_state=int(cfg.get("seed", 3407)),
        use_rslora=False,
        loftq_config=None,
    )

    train_rows = load_jsonl_messages(cfg["train_file"])
    dataset = Dataset.from_list(train_rows)

    def formatting_prompts_func(examples):
        texts = [
            tokenizer.apply_chat_template(convo, tokenize=False, add_generation_prompt=False)
            for convo in examples["messages"]
        ]
        return {"text": texts}

    dataset = dataset.map(formatting_prompts_func, batched=True, remove_columns=dataset.column_names)

    args_kwargs = dict(
        per_device_train_batch_size=int(cfg["per_device_train_batch_size"]),
        gradient_accumulation_steps=int(cfg["gradient_accumulation_steps"]),
        warmup_steps=int(cfg["warmup_steps"]),
        learning_rate=float(cfg["learning_rate"]),
        fp16=not is_bfloat16_supported(),
        bf16=is_bfloat16_supported(),
        logging_steps=int(cfg["logging_steps"]),
        optim="adamw_8bit",
        weight_decay=0.001,
        lr_scheduler_type="linear",
        seed=int(cfg.get("seed", 3407)),
        output_dir=cfg["output_dir"],
        report_to=cfg.get("report_to", "none"),
    )
    if cfg.get("num_train_epochs"):
        args_kwargs["num_train_epochs"] = float(cfg["num_train_epochs"])
    else:
        args_kwargs["max_steps"] = int(cfg["max_steps"])

    trainer = SFTTrainer(
        model=model,
        tokenizer=tokenizer,
        train_dataset=dataset,
        dataset_text_field="text",
        max_seq_length=max_seq_length,
        data_collator=DataCollatorForSeq2Seq(tokenizer=tokenizer),
        packing=bool(cfg.get("packing", False)),
        args=SFTConfig(**args_kwargs),
    )

    if cfg.get("train_on_responses_only"):
        from unsloth.chat_templates import train_on_responses_only
        trainer = train_on_responses_only(
            trainer,
            instruction_part=cfg["instruction_part"],
            response_part=cfg["response_part"],
        )

    print("Starting training with config:")
    print(json.dumps({k: v for k, v in cfg.items() if "token" not in k.lower()}, indent=2))
    trainer_stats = trainer.train()
    print(trainer_stats)

    adapter_dir = cfg.get("adapter_dir", "adapters/final")
    Path(adapter_dir).parent.mkdir(parents=True, exist_ok=True)
    model.save_pretrained(adapter_dir)
    tokenizer.save_pretrained(adapter_dir)
    print(f"Saved LoRA adapter to {adapter_dir}")

    if cfg.get("save_merged_16bit"):
        model.save_pretrained_merged("merged_16bit", tokenizer, save_method="merged_16bit")
        print("Saved merged 16-bit model to merged_16bit")
    if cfg.get("save_gguf"):
        quant = cfg.get("gguf_quantization", "q4_k_m")
        model.save_pretrained_gguf("gguf", tokenizer, quantization_method=quant)
        print(f"Saved GGUF model to gguf ({quant})")


if __name__ == "__main__":
    main()
'''


CHAT_PY = r'''#!/usr/bin/env python3
"""Chat with the base model or your fine-tuned LoRA adapter."""
from __future__ import annotations

import argparse
import json
from pathlib import Path


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--base", action="store_true", help="chat with the base model instead of the adapter")
    parser.add_argument("--max-new-tokens", type=int, default=256)
    args = parser.parse_args()
    cfg = json.loads(Path("config.json").read_text())

    from unsloth import FastLanguageModel
    import torch

    model_name = cfg["base_model"] if args.base else cfg.get("adapter_dir", "adapters/final")
    model, tokenizer = FastLanguageModel.from_pretrained(
        model_name=model_name,
        max_seq_length=int(cfg["max_seq_length"]),
        dtype=None,
        load_in_4bit=bool(cfg.get("load_in_4bit", True)),
        token=cfg.get("hf_token"),
    )
    chat_template = cfg.get("chat_template", "auto")
    if chat_template and chat_template != "auto":
        from unsloth.chat_templates import get_chat_template
        tokenizer = get_chat_template(tokenizer, chat_template=chat_template)
    FastLanguageModel.for_inference(model)

    print("Type a message. Ctrl-D/Ctrl-C to exit.")
    messages = []
    system_prompt = cfg.get("system_prompt")
    if system_prompt:
        messages.append({"role": "system", "content": system_prompt})
    while True:
        try:
            user = input("\nuser> ").strip()
        except (EOFError, KeyboardInterrupt):
            print("\nbye")
            break
        if not user:
            continue
        messages.append({"role": "user", "content": user})
        inputs = tokenizer.apply_chat_template(
            messages,
            tokenize=True,
            add_generation_prompt=True,
            return_tensors="pt",
        ).to("cuda" if torch.cuda.is_available() else "cpu")
        outputs = model.generate(
            input_ids=inputs,
            max_new_tokens=args.max_new_tokens,
            use_cache=True,
            temperature=0.7,
            min_p=0.1,
        )
        text = tokenizer.decode(outputs[0][inputs.shape[-1]:], skip_special_tokens=True).strip()
        print(f"assistant> {text}")
        messages.append({"role": "assistant", "content": text})


if __name__ == "__main__":
    main()
'''


EVAL_PY = r'''#!/usr/bin/env python3
"""Tiny before/after eval runner for held-out chat JSONL examples.

Scores exact/substring matches against the held-out assistant answer. This is a
starter eval, not a replacement for a real benchmark or human review.
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path


def load_examples(path):
    with open(path, "r", encoding="utf-8") as f:
        for line in f:
            if not line.strip():
                continue
            obj = json.loads(line)
            messages = obj["messages"]
            if messages[-1]["role"] != "assistant":
                continue
            yield messages[:-1], messages[-1]["content"]


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--base", action="store_true", help="evaluate the base model instead of adapter")
    parser.add_argument("--limit", type=int, default=20)
    parser.add_argument("--max-new-tokens", type=int, default=256)
    args = parser.parse_args()
    cfg = json.loads(Path("config.json").read_text())

    from unsloth import FastLanguageModel
    import torch

    model_name = cfg["base_model"] if args.base else cfg.get("adapter_dir", "adapters/final")
    model, tokenizer = FastLanguageModel.from_pretrained(
        model_name=model_name,
        max_seq_length=int(cfg["max_seq_length"]),
        dtype=None,
        load_in_4bit=bool(cfg.get("load_in_4bit", True)),
        token=cfg.get("hf_token"),
    )
    chat_template = cfg.get("chat_template", "auto")
    if chat_template and chat_template != "auto":
        from unsloth.chat_templates import get_chat_template
        tokenizer = get_chat_template(tokenizer, chat_template=chat_template)
    FastLanguageModel.for_inference(model)

    total = 0
    contains = 0
    out_path = Path("eval_outputs_base.jsonl" if args.base else "eval_outputs_adapter.jsonl")
    with out_path.open("w", encoding="utf-8") as out:
        for messages, expected in load_examples(cfg.get("eval_file", "data/eval.jsonl")):
            if total >= args.limit:
                break
            inputs = tokenizer.apply_chat_template(messages, tokenize=True, add_generation_prompt=True, return_tensors="pt").to("cuda" if torch.cuda.is_available() else "cpu")
            outputs = model.generate(input_ids=inputs, max_new_tokens=args.max_new_tokens, use_cache=True, temperature=0.0)
            text = tokenizer.decode(outputs[0][inputs.shape[-1]:], skip_special_tokens=True).strip()
            ok = expected.strip().lower() in text.lower() or text.lower() in expected.strip().lower()
            contains += int(ok)
            total += 1
            out.write(json.dumps({"prompt": messages, "expected": expected, "got": text, "contains_match": ok}, ensure_ascii=False) + "\n")
            print(f"[{total}] {'✅' if ok else '❌'} expected={expected[:80]!r} got={text[:80]!r}")
    print(f"\nSubstring score: {contains}/{total} = {(contains / max(total, 1)):.1%}")
    print(f"Wrote detailed outputs to {out_path}")


if __name__ == "__main__":
    main()
'''


START_HERE = '''# Start here

You have a generated UnslothKit project for `{task}`.

## 1. Check your data

```bash
unslothkit data check data/train.jsonl
unslothkit data check data/eval.jsonl
```

If `unslothkit` is not found, install it once from the cloned repo with `./scripts/install-cli.sh`, or run data checks from the cloned UnslothKit repo with `python3 -m unslothkit ...`.

Open `data/train.jsonl` and replace the sample examples with your real examples.

## 2. Baseline first

In your GPU/Unsloth environment:

```bash
python eval.py --base
```

This shows what the base model does before fine-tuning.

## 3. Train

```bash
python train.py
```

The LoRA adapter saves to `adapters/final`.

## 4. Compare + chat

```bash
python eval.py
python chat.py
python chat.py --base
```

If outputs are bad, add examples for those failure cases, run data check again, and retrain.

## 5. Edit config

`config.json` is the only file most beginners need to edit. Start with:

- `max_steps`: keep small for smoke tests, increase later
- `base_model`: change only after the pipeline works
- `max_seq_length`: increase only if examples are being truncated

'''


PROJECT_README = '''# {project_name}

Generated by **UnslothKit** for task: `{task}`.

UnslothKit is an independent community starter layer for Unsloth. All credit for Unsloth itself goes to the Unsloth team. For official Unsloth docs, use https://unsloth.ai/docs.

License reminder: this generated scaffold is a starter project. Unsloth, base models, and datasets have their own licenses/terms; check them before redistribution or commercial use.

## Quick start

If `unslothkit` is not found, install it once from the cloned repo with `./scripts/install-cli.sh`, or use `python3 -m unslothkit ...` from the repo.

```bash
# 1) Inspect the data first
unslothkit data check data/train.jsonl

# 2) Install training deps in a GPU environment
curl -LsSf https://astral.sh/uv/install.sh | sh
uv venv unsloth_env --python 3.13
source unsloth_env/bin/activate
uv pip install unsloth --torch-backend=auto

# 3) Smoke-test train
python train.py

# 4) Chat / evaluate
python chat.py
python eval.py --base
python eval.py
```

## What to edit

- `START_HERE.md`: beginner step-by-step guide.
- `config.json`: model, LoRA rank, steps, max sequence length, export options.
- `data/train.jsonl`: training examples.
- `data/eval.jsonl`: held-out examples. Do not train on these.

## Task hint

{task_hint}

## Data format

Each line should be:

```json
{{"messages": [{{"role": "user", "content": "..."}}, {{"role": "assistant", "content": "..."}}]}}
```

Run `unslothkit data check data/train.jsonl` after every data edit.
'''


def create_project(path: Path, task: str, model_label: str, force: bool = False) -> None:
    if path.exists() and any(path.iterdir()) and not force:
        raise FileExistsError(f"{path} already exists and is not empty; pass --force to overwrite generated files")
    path.mkdir(parents=True, exist_ok=True)
    (path / "data").mkdir(exist_ok=True)
    (path / "adapters").mkdir(exist_ok=True)
    (path / "notes").mkdir(exist_ok=True)

    cfg = default_config(project_name=path.name, task=task, model_label=model_label)
    (path / "config.json").write_text(json.dumps(cfg, indent=2) + "\n", encoding="utf-8")
    (path / "train.py").write_text(TRAIN_PY, encoding="utf-8")
    (path / "chat.py").write_text(CHAT_PY, encoding="utf-8")
    (path / "eval.py").write_text(EVAL_PY, encoding="utf-8")
    (path / "START_HERE.md").write_text(START_HERE.format(task=task), encoding="utf-8")
    (path / "README.md").write_text(PROJECT_README.format(project_name=path.name, task=task, task_hint=task_hint(task)), encoding="utf-8")
    write_sample(path / "data" / "train.jsonl", task=task)
    write_sample(path / "data" / "eval.jsonl", task=task)
    (path / "notes" / "plan.md").write_text(dedent(f"""
    # Fine-tuning plan

    ## Goal
    Build a better model for `{task}`.

    ## Baseline
    - Run `python eval.py --base` before training.
    - Save examples where the base model fails.

    ## First experiment
    - Model: `{cfg['base_model']}`
    - Steps: `{cfg['max_steps']}`
    - LoRA rank: `{cfg['lora_rank']}`
    - Success: eval examples and manual chat feel closer to the desired behavior.

    ## Next iteration
    - Add 20-100 higher-quality examples from failure cases.
    - Keep eval data separate.
    - Compare base vs adapter before increasing model size.
    """).lstrip(), encoding="utf-8")
